### ISSUE TITLE
how to exclude files/dirs?

### ISSUE THREAD

**Issue by sandric** [thomasfl/filewatcher#20]
Hi, I saw on shell command section, that there's an ability to exclude nodes from patterns, but I do not really see how is it implemented in library.. Can you please point me to code for me to understand in how to use it via library, e.g. requiring gem from my script and creating an instance. thx.

**Comment by thomasfl** [comment]
I never use the exclude pattern myself.

There is really nothing to it if you use the gem from ruby: 


    require 'rubygems
    require 'filewatcher'

    FileWatcher.new(["file1", "file2", "file3"]).watch do |filename|
      puts "File " + filename + " was changed"
    end

**Comment by DannyBen** [comment]
Why is this ticket closed? 

This seems to be either a documentation bug or an unimplemented feature.

The [README states there is a `-x, --exclude <s>`](https://github.com/thomasfl/filewatcher#command-line-options) but there seem to be no support for it anywhere in the code. The only reference to it [is here](https://github.com/thomasfl/filewatcher/blob/master/bin/filewatcher#L31).

It would be nice if this is implemented, and something is added to the docs to show how to exclude several patterns.

**Comment by thomasfl** [comment]
You are right. Exlude files and dirs would be nice. I don't know what the api would look like. The only idea I got is to let the API take two string arrays as input. The first would contain file name patterns to include and the second file names to exclude.

**Comment by DannyBen** [comment]
Yes. Well regardless of the end implementation (and if at all you decide to implement), the README should be updated to reflect the fact that its not there (need to remove the `--exclude` flag that is mentioned there.

As for ideas for implementation, I would like to suggest keeping the library API and the command line API as close as possible to each other, and to keep the include/exclude patterns similar if possible.

When I tried to see if the `--exclude` flag works, I tried some things like:
1. `--exclude "tmp/,log/"` (comma separated)
2. `--exclude "tmp/ log/"` (space separated)
3. `--exclude "^(tmp|log)" (regex)

The exclude can either be a path spec (like the include) or a regex in my opinion. Path spec is preferred I think since it is more in line with the include parameter.

Of course, as you mentioned, the lack of this feature is less critical when using the library, since you can easily `do something unless filename =~ /rule/` but I find myself liking the command line call even when running through ruby.

**Comment by thomasfl** [comment]
I have started to work on this in a new branch called [exclude](https://github.com/thomasfl/filewatcher/tree/exclude) 

The API has been changed to use named parameters as you suggested. I haven't found a way yet to tell if a filename matches one of the exclusion filename patterns. Pure regexp is no good since Regexp.new("*.rb") returns a regexp pattern format error.

```ruby
    if(filename.match(Regexp.new(exclude_filename)))
        exclude = true
    end
```

The best strategy is probably to use the same expand_directories() method on the exclusion files and the diff the inclusion and exclusion filename list. That way the format for filename glob pattern will be the same.

**Comment by DannyBen** [comment]
Sounds like `expand_directories` may indeed be better than a regex. I think regex would be alien to such a utility anyway.

Let me know if I can help or you want to bounce ideas.

**Comment by thomasfl** [comment]
You're welcome to submit pull request to the feature branch. :-)

**Comment by thomasfl** [comment]
I've implemented the API and the tests passes. The command line interface still needs to be updated. I'll see if I can do it tomorrow. So far I've managed to do it in 20 lines of code. Small is beautiful, I will have to think about a way to shorten it. :-)

**Comment by thomasfl** [comment]
@DannyBen @penntaylor I have finally released a new version of the gem where the --exclude files option works both in the command line and from the ruby api:

    $ filewatcher '**/*.*' --exclude '**/*.rb' --spinner --interval 0.1 'echo $FILENAME'

    FileWatcher.new('**/*.*', exclude: '**/*.rb', spinner: true, interval: 0.1).watch() do |filename|
        puts filename
    end

**Comment by DannyBen** [comment]
excellent, thanks.
