### ISSUE TITLE
Version 0.5.0 breaks the nice Ctrl+C interrupt

### ISSUE THREAD

**Issue by DannyBen** [thomasfl/filewatcher#24]
Hi,

I think version 0.5.0 broke the nice (without stack trace)  Ctrl+C interrupt.
In my code I have my own trap for SIGINT, that simply says a nice "Goodbye".

Up until now (with 0.4.0) it worked very nicely, with 0.5.0 it does not.

I should mention that I am forking several filewatcher processes.

(Also I wish the spinner was disabled by default).

If a repro case is required, I can try and make one.

EDIT:
I have created the smallest repro case I could make.
Available in [this gist](https://gist.github.com/DannyBen/868952bb0879fb6b990c)

And attaching a screencast of the issue.
![anim](https://cloud.githubusercontent.com/assets/2405099/7787671/680bd7a6-0220-11e5-886c-05c0d87f210f.gif)

**Comment by thomasfl** [comment]
Thanks for your feedback and screencast. The last pull-request was the biggest so far, and I clearly didn't test filewatcher enough. The spinner was my idea, but should clearly be optional. It interfers with output from stdout. I have to have a look at it tomorrow.

**Comment by thomasfl** [comment]
There is a new version 0.51 available from now on github that exists silently on sigint. I haven't pushed the gem yet, but please install it from the repo and tell me what you think:

```
    git clone https://github.com/thomasfl/filewatcher.git
    cd filewatcher
    gem build filewatcher.gemspec
    gem install filewatcher-0.5.1.gem
```

The spinner is now optional via the --spinner option.

BTW! Have you tried the --restart option? It speeds up autotesting so much that I have concidered making it default. It makes filewatcher fork a new process that the shell commands run in, and instead of waiting for the command to finish on file system updates, it starts up a new process and kills the old process in the background.

**Comment by DannyBen** [comment]
Excellent. Will test a little later and report back.
(Havent tested --restart yet).

**Comment by thomasfl** [comment]
Thanks for your feedback Danny!

I'll change the text from "scanning" to "watching".

The speed increase with the --restart option is noticeable on my laptop. A better name for the option would be --background, because it runs the shell command in the background in a separate fork. If you use filewatcher for autotesting, and saves a source file several times with short interval between each time, then you'll notice the difference.

**Comment by DannyBen** [comment]
I see.

I will try that feature in my day to day use.

Since this feature is also doing some process forking trickery, I would be cautious about making it the default operation. Maybe let it be like it is now for a while, see if people report problems, and then decide if it should be the default or not in one of the future major releases.

**Comment by thomasfl** [comment]
I've changed the text displayed next to the scanner from "scanning" to "watching" and pushed the new 0.5.1 to the rubygems.org repository.

Thanks again for taking the time to test filewatcher.

**Comment by DannyBen** [comment]
My pleasure, thanks for the quick fix.
