### ISSUE TITLE
When used with multiple watch paths block vars are improperly assigned

### ISSUE THREAD

**Issue by ngzax** [thomasfl/filewatcher#75]
When I create a new Filewatcher with an array of paths it does not properly assign the block vars. Instead I get a Hash assigned to the first variable.

```
Filewatcher.new(watch_dirs).watch do |fn, ev|
```

fn will now contain 

```
{"/path/to/index.md"=>:deleted}
```

ev is empty.

Notice also, that the event is also :deleted and is not :changed like it should be.

I have validated that this does work properly using the gem version of filewatcher, albeit you now have to use File**W**atcher.new, not Filewatcher.new

**Comment by AlexWayfer** [comment]
Hello!

You're absolutely right. I'm sorry, I'll try to fix this soon (and cover by tests).

**Comment by ngzax** [comment]
No worries! Just thought you'd like to know. Thanks for providing this gem, it's nice and lightweight. I am using it for one of my projects, https://github.com/ngzax/urbit-sync

**Comment by AlexWayfer** [comment]
@ngzax, some news:
*   `changes` argument instead of `fn, en` should be, it's correct for now
*   `README` is incorrect about this
*   But I decided to throw `every` option to Ruby API, and calling block with `filename, event` arguments (calling multiple times with `every` option), almost like in the `README` now
*   `README` is fixed (on my local), I'm fixing (and completing) tests

Stay tuned :ok_hand:

**Comment by AlexWayfer** [comment]
* Tests fixed
* Bug with permanent `deleted` event fixed
* Tests supplemented

You can track the fight between me and Travis CI in #76 now.

**Comment by ngzax** [comment]
I have verified that this is now working properly. Thanks for the quick fix.
