### ISSUE TITLE
1.0 Release -- event 'updated' raises NotImplementedError

### ISSUE THREAD

**Issue by dariusatmarsnowe** [thomasfl/filewatcher#80]
After the latest update, I'm running into an error:
`NotImplementedError: Unknown event -- updated -- templates/product.liquid`

This is occuring in the watch method below:
`        action = if [:changed, :new].include?(event)
          :send_asset
        elsif event == :delete
          :delete_asset
        else
          raise NotImplementedError, "Unknown event -- #{event} -- #{filename}"
        end`

I also ran into a case sensitivity issue calling FileWatcher.new() rather than Filewatcher.new() for those who may run into the same.

**Comment by ngzax** [comment]
The action used to be :changed now it is :updated. your code is expecting :changed.

**Comment by dariusatmarsnowe** [comment]
Thanks @ngzax. Appreciate the quick response.

**Comment by AlexWayfer** [comment]
@dariusatmarsnowe, thank you for feedback! Info about events renaming added to [release description](https://github.com/thomasfl/filewatcher/releases/tag/v1.0.0).

@ngzax, thank you for help!

> I also ran into a case sensitivity issue calling FileWatcher.new() rather than Filewatcher.new() for those who may run into the same.

Yes, this is described in release. It's so because downcased version of `FileWatcher` is `file_watcher`, not `filewatcher`.

**Comment by ngzax** [comment]
you're welcome. thanks again for your work on this excellent library.
